### ISSUE TITLE
What's the way you automate the great commit log messages?

### ISSUE THREAD

**Issue by aborruso** [simonw/pge-outages#2]
Hi @simonw ,
in the file history we have great and readable commit messages, like this `pge-outages: 8 outages added, 6 outages removed, 20 outages changed`.

What's the way you generate them?

Thank you

![image](https://user-images.githubusercontent.com/30607/110199789-6f09c600-7e5a-11eb-9018-147b95e861b0.png)

**Comment by pax** [comment]
the data is generated by another repository: [simonw/disaster-scrapers](https://github.com/simonw/disaster-scrapers)
look into `disaster_scrapers.py` and `pge.py`
